// templates/designer-template/src/components/ui/item.tsx
import * as React from "react"
import { mergeProps } from "@base-ui/react/merge-props"
import { useRender } from "@base-ui/react/use-render"
import { cva, type VariantProps } from "class-variance-authority"

import { cn } from "@/lib/utils"
import { Separator } from "@/components/ui/separator"

function ItemGroup({ className, ...props }: React.ComponentProps<"div">) {
  return (
    <div
      role="list"
      data-slot="item-group"
      className={cn(
        "group/item-group flex w-full flex-col gap-4 has-data-[size=sm]:gap-2.5 has-data-[size=xs]:gap-2",
        className
      )}
      {...props}
    />
  )
}

function ItemSeparator({
  className,
  ...props
}: React.ComponentProps<typeof Separator>) {
  return (
    <Separator
      data-slot="item-separator"
      orientation="horizontal"
      className={cn("my-2", className)}
      {...props}
    />
  )
}

const itemVariants = cva(
  "group/item flex w-full flex-wrap items-center rounded-lg border text-sm transition-colors duration-100 outline-none focus-visible:border-ring focus-visible:ring-[3px] focus-visible:ring-ring/50 [a]:transition-colors [a]:hover:bg-muted",
  {
    variants: {
      variant: {
        default: "border-transparent",
        outline: "border-border",
        muted: "border-transparent bg-muted/50",
      },
      size: {
        default: "gap-2.5 px-3 py-2.5",
        sm: "gap-2.5 px-3 py-2.5",
        xs: "gap-2 px-2.5 py-2 in-data-[slot=dropdown-menu-content]:p-0",
      },
    },
    defaultVariants: {
      variant: "default",
      size: "default",
    },
  }
)

function Item({
  className,
  variant = "default",
  size = "default",
  render,
  ...props
}: useRender.ComponentProps<"div"> & VariantProps<typeof itemVariants>) {
  return useRender({
    defaultTagName: "div",
    props: mergeProps<"div">(
      {
        className: cn(itemVariants({ variant, size, className })),
      },
      props
    ),
    render,
    state: {
      slot: "item",
      variant,
      size,
    },
  })
}

const itemMediaVariants = cva(
  "flex shrink-0 items-center justify-center gap-2 group-has-data-[slot=item-description]/item:translate-y-0.5 group-has-data-[slot=item-description]/item:self-start [&_svg]:pointer-events-none",
  {
    variants: {
      variant: {
        default: "bg-transparent",
        icon: "[&_svg]:fill-current [&_svg:not([class*='size-'])]:size-4",
        image:
          "size-10 overflow-hidden rounded-sm group-data-[size=sm]/item:size-8 group-data-[size=xs]/item:size-6 [&_img]:size-full [&_img]:object-cover",
      },
    },
    defaultVariants: {
      variant: "default",
    },
  }
)

function ItemMedia({
  className,
  variant = "default",
  ...props
}: React.ComponentProps<"div"> & VariantProps<typeof itemMediaVariants>) {
  return (
    <div
      data-slot="item-media"
      data-variant={variant}
      className={cn(itemMediaVariants({ variant, className }))}
      {...props}
    />
  )
}

function ItemContent({ className, ...props }: React.ComponentProps<"div">) {
  return (
    <div
      data-slot="item-content"
      className={cn(
        "flex flex-1 flex-col gap-1 group-data-[size=xs]/item:gap-0 [&+[data-slot=item-content]]:flex-none",
        className
      )}
      {...props}
    />
  )
}

function ItemTitle({ className, ...props }: React.ComponentProps<"div">) {
  return (
    <div
      data-slot="item-title"
      className={cn(
        "line-clamp-1 flex w-fit items-center gap-2 text-sm leading-snug font-medium underline-offset-4",
        className
      )}
      {...props}
    />
  )
}

function ItemDescription({ className, ...props }: React.ComponentProps<"p">) {
  return (
    <p
      data-slot="item-description"
      className={cn(
        "line-clamp-2 text-left text-sm leading-normal font-normal text-muted-foreground group-data-[size=xs]/item:text-xs [&>a]:underline [&>a]:underline-offset-4 [&>a:hover]:text-primary",
        className
      )}
      {...props}
    />
  )
}

function ItemActions({ className, ...props }: React.ComponentProps<"div">) {
  return (
    <div
      data-slot="item-actions"
      className={cn("flex items-center gap-2", className)}
      {...props}
    />
  )
}

function ItemHeader({ className, ...props }: React.ComponentProps<"div">) {
  return (
    <div
      data-slot="item-header"
      className={cn(
        "flex basis-full items-center justify-between gap-2",
        className
      )}
      {...props}
    />
  )
}

function ItemFooter({ className, ...props }: React.ComponentProps<"div">) {
  return (
    <div
      data-slot="item-footer"
      className={cn(
        "flex basis-full items-center justify-between gap-2",
        className
      )}
      {...props}
    />
  )
}

export {
  Item,
  ItemMedia,
  ItemContent,
  ItemActions,
  ItemGroup,
  ItemSeparator,
  ItemTitle,
  ItemDescription,
  ItemHeader,
  ItemFooter,
}

// packages/registry-angular/ui/item/item.component.ts
import { ChangeDetectionStrategy, Component, computed, input } from "@angular/core"

import { cn } from "@/lib/utils"
import {
  itemMediaVariants,
  itemVariants,
  type ItemMediaVariant,
  type ItemSize,
  type ItemVariant,
} from "./item.variants"

/**
 * Angular port of @force-ui/item (radix-force-ui style).
 *
 * A list-row primitive: media (icon/image/avatar) + title/description +
 * actions, optionally grouped with ItemGroup / ItemSeparator.
 *
 * All sub-components use attribute selectors so the host element's semantics
 * are caller-controlled — an `<a uiItem href="…">` is Angular's equivalent of
 * React's `asChild` / Vue's `as-child`, no extra prop needed.
 *
 * Usage:
 *   <div uiItem variant="outline">
 *     <div uiItemMedia variant="icon"><svg>…</svg></div>
 *     <div uiItemContent>
 *       <div uiItemTitle>Title</div>
 *       <p uiItemDescription>Description</p>
 *     </div>
 *     <div uiItemActions><button uiButton size="sm">Action</button></div>
 *   </div>
 */
@Component({
  selector: "[uiItem]",
  standalone: true,
  templateUrl: "./item.component.html",
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    "data-slot": "item",
    "[attr.data-variant]": "variant()",
    "[attr.data-size]": "size()",
    "[class]": "classes()",
  },
})
export class ItemComponent {
  readonly variant = input<ItemVariant>("default")
  readonly size = input<ItemSize>("default")
  readonly className = input<string | undefined>(undefined, { alias: "class" })

  protected readonly classes = computed(() =>
    cn(itemVariants({ variant: this.variant(), size: this.size() }), this.className())
  )
}

@Component({
  selector: "[uiItemGroup]",
  standalone: true,
  templateUrl: "./item.component.html",
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    role: "list",
    "data-slot": "item-group",
    "[class]": "classes()",
  },
})
export class ItemGroupComponent {
  readonly className = input<string | undefined>(undefined, { alias: "class" })

  protected readonly classes = computed(() =>
    cn("cn-item-group group/item-group flex w-full flex-col", this.className())
  )
}

/**
 * ItemSeparator is self-contained rather than composed with SeparatorComponent.
 *
 * React renders `<Separator data-slot="item-separator" …/>`, but Angular
 * refuses to instantiate two components on one host element (NG0300), so
 * `<div uiSeparator uiItemSeparator>` is not a legal translation while
 * SeparatorComponent is a @Component. This class therefore replicates
 * SeparatorComponent's base classes and host attributes for the fixed
 * horizontal, decorative case React hardcodes, producing the same DOM as the
 * React source. Keep the base class string in sync with
 * ui/separator/separator.component.ts. See DIVERGENCES.md §item-1.
 */
@Component({
  selector: "[uiItemSeparator]",
  standalone: true,
  templateUrl: "./item.component.html",
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    "data-slot": "item-separator",
    role: "none",
    "data-orientation": "horizontal",
    "[class]": "classes()",
  },
})
export class ItemSeparatorComponent {
  readonly className = input<string | undefined>(undefined, { alias: "class" })

  protected readonly classes = computed(() =>
    cn(
      "shrink-0 bg-border data-[orientation=horizontal]:h-px data-[orientation=horizontal]:w-full data-[orientation=vertical]:w-px data-[orientation=vertical]:self-stretch",
      "cn-item-separator",
      this.className()
    )
  )
}

@Component({
  selector: "[uiItemMedia]",
  standalone: true,
  templateUrl: "./item.component.html",
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    "data-slot": "item-media",
    "[attr.data-variant]": "variant()",
    "[class]": "classes()",
  },
})
export class ItemMediaComponent {
  readonly variant = input<ItemMediaVariant>("default")
  readonly className = input<string | undefined>(undefined, { alias: "class" })

  protected readonly classes = computed(() =>
    cn(itemMediaVariants({ variant: this.variant() }), this.className())
  )
}

@Component({
  selector: "[uiItemContent]",
  standalone: true,
  templateUrl: "./item.component.html",
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    "data-slot": "item-content",
    "[class]": "classes()",
  },
})
export class ItemContentComponent {
  readonly className = input<string | undefined>(undefined, { alias: "class" })

  protected readonly classes = computed(() =>
    cn(
      "cn-item-content flex flex-1 flex-col [&+[data-slot=item-content]]:flex-none",
      this.className()
    )
  )
}

@Component({
  selector: "[uiItemTitle]",
  standalone: true,
  templateUrl: "./item.component.html",
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    "data-slot": "item-title",
    "[class]": "classes()",
  },
})
export class ItemTitleComponent {
  readonly className = input<string | undefined>(undefined, { alias: "class" })

  protected readonly classes = computed(() =>
    cn("cn-item-title line-clamp-1 flex w-fit items-center", this.className())
  )
}

@Component({
  selector: "[uiItemDescription]",
  standalone: true,
  templateUrl: "./item.component.html",
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    "data-slot": "item-description",
    "[class]": "classes()",
  },
})
export class ItemDescriptionComponent {
  readonly className = input<string | undefined>(undefined, { alias: "class" })

  protected readonly classes = computed(() =>
    cn(
      "cn-item-description line-clamp-2 font-normal [&>a]:underline [&>a]:underline-offset-4 [&>a:hover]:text-primary",
      this.className()
    )
  )
}

@Component({
  selector: "[uiItemActions]",
  standalone: true,
  templateUrl: "./item.component.html",
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    "data-slot": "item-actions",
    "[class]": "classes()",
  },
})
export class ItemActionsComponent {
  readonly className = input<string | undefined>(undefined, { alias: "class" })

  protected readonly classes = computed(() =>
    cn("cn-item-actions flex items-center", this.className())
  )
}

@Component({
  selector: "[uiItemHeader]",
  standalone: true,
  templateUrl: "./item.component.html",
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    "data-slot": "item-header",
    "[class]": "classes()",
  },
})
export class ItemHeaderComponent {
  readonly className = input<string | undefined>(undefined, { alias: "class" })

  protected readonly classes = computed(() =>
    cn(
      "cn-item-header flex basis-full items-center justify-between",
      this.className()
    )
  )
}

@Component({
  selector: "[uiItemFooter]",
  standalone: true,
  templateUrl: "./item.component.html",
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    "data-slot": "item-footer",
    "[class]": "classes()",
  },
})
export class ItemFooterComponent {
  readonly className = input<string | undefined>(undefined, { alias: "class" })

  protected readonly classes = computed(() =>
    cn(
      "cn-item-footer flex basis-full items-center justify-between",
      this.className()
    )
  )
}
