// templates/designer-template/src/components/ui/accordion.tsx
import { Accordion as AccordionPrimitive } from "@base-ui/react/accordion"

import { cn } from "@/lib/utils"
import { ChevronDownIcon, ChevronUpIcon } from "@/lib/material-symbols"

function Accordion({ className, ...props }: AccordionPrimitive.Root.Props) {
  return (
    <AccordionPrimitive.Root
      data-slot="accordion"
      className={cn("flex w-full flex-col", className)}
      {...props}
    />
  )
}

function AccordionItem({ className, ...props }: AccordionPrimitive.Item.Props) {
  return (
    <AccordionPrimitive.Item
      data-slot="accordion-item"
      className={cn("not-last:border-b", className)}
      {...props}
    />
  )
}

function AccordionTrigger({
  className,
  children,
  ...props
}: AccordionPrimitive.Trigger.Props) {
  return (
    <AccordionPrimitive.Header className="flex">
      <AccordionPrimitive.Trigger
        data-slot="accordion-trigger"
        className={cn(
          "group/accordion-trigger relative flex flex-1 items-start justify-between rounded-lg border border-transparent py-2.5 text-left text-sm font-medium transition-all outline-none hover:underline focus-visible:border-ring focus-visible:ring-3 focus-visible:ring-ring/50 focus-visible:after:border-ring aria-disabled:pointer-events-none aria-disabled:opacity-50 **:data-[slot=accordion-trigger-icon]:ml-auto **:data-[slot=accordion-trigger-icon]:size-4 **:data-[slot=accordion-trigger-icon]:text-muted-foreground group-aria-expanded/accordion-trigger:**:data-[slot=accordion-trigger-icon]:text-foreground",
          className
        )}
        {...props}
      >
        {children}
        <ChevronDownIcon materialSymbols="keyboard_arrow_down" data-slot="accordion-trigger-icon" className="pointer-events-none shrink-0 group-aria-expanded/accordion-trigger:hidden" />
        <ChevronUpIcon materialSymbols="keyboard_arrow_up" data-slot="accordion-trigger-icon" className="pointer-events-none hidden shrink-0 group-aria-expanded/accordion-trigger:inline" />
      </AccordionPrimitive.Trigger>
    </AccordionPrimitive.Header>
  )
}

function AccordionContent({
  className,
  children,
  ...props
}: AccordionPrimitive.Panel.Props) {
  return (
    <AccordionPrimitive.Panel
      data-slot="accordion-content"
      className="overflow-hidden text-sm motion-reduce:animate-none data-open:animate-accordion-down data-closed:animate-accordion-up"
      {...props}
    >
      <div
        className={cn(
          "h-(--accordion-panel-height) pt-0 pb-2.5 data-ending-style:h-0 data-starting-style:h-0 [&_a]:underline [&_a]:underline-offset-3 [&_a]:hover:text-foreground [&_p:not(:last-child)]:mb-4",
          className
        )}
      >
        {children}
      </div>
    </AccordionPrimitive.Panel>
  )
}

export { Accordion, AccordionItem, AccordionTrigger, AccordionContent }

// apps/preview-angular/src/angular-ui/accordion/accordion.component.ts
import {
  booleanAttribute,
  ChangeDetectionStrategy,
  Component,
  computed,
  inject,
  input,
} from "@angular/core"
import { DomSanitizer, type SafeHtml } from "@angular/platform-browser"
import {
  injectAccordionItemContext,
  RdxAccordionHeaderDirective,
  RdxAccordionItemDirective,
  RdxAccordionPanelDirective,
  RdxAccordionRootDirective,
  RdxAccordionTriggerDirective,
} from "@radix-ng/primitives/accordion"

import { cn } from "@/lib/utils"

const CHEVRON_DOWN_SVG = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 -960 960 960"><path d="M480-345 240-585l56-56 184 184 184-184 56 56-240 240Z"/></svg>`

/**
 * Angular port of @force-ui/accordion (radix-force-ui style).
 * Uses @radix-ng/primitives v1.x API.
 *
 * Usage:
 *   <div uiAccordion [multiple]="false">
 *     <div uiAccordionItem value="item-1">
 *       <div uiAccordionTrigger>Is it accessible?</div>
 *       <div uiAccordionContent>Yes. It uses WAI-ARIA design patterns.</div>
 *     </div>
 *   </div>
 *
 * Note: v1.x uses [multiple] instead of type="single"|"multiple" + collapsible.
 */
@Component({
  selector: "[uiAccordion]",
  standalone: true,
  template: "<ng-content />",
  changeDetection: ChangeDetectionStrategy.OnPush,
  hostDirectives: [
    {
      directive: RdxAccordionRootDirective,
      inputs: ["value", "defaultValue", "multiple", "disabled", "orientation"],
      outputs: ["valueChange", "onValueChange"],
    },
  ],
  host: {
    "data-slot": "accordion",
    "[class]": "classes()",
  },
})
export class AccordionComponent {
  readonly className = input<string | undefined>(undefined, { alias: "class" })
  protected readonly classes = computed(() => cn("flex w-full flex-col", this.className()))
}

@Component({
  selector: "[uiAccordionItem]",
  standalone: true,
  template: "<ng-content />",
  changeDetection: ChangeDetectionStrategy.OnPush,
  hostDirectives: [
    {
      directive: RdxAccordionItemDirective,
      inputs: ["value", "disabled"],
      outputs: ["onOpenChange"],
    },
  ],
  host: {
    "data-slot": "accordion-item",
    "[class]": "classes()",
  },
})
export class AccordionItemComponent {
  readonly className = input<string | undefined>(undefined, { alias: "class" })
  protected readonly classes = computed(() => cn("cn-accordion-item border-border", this.className()))
}

@Component({
  selector: "[uiAccordionTrigger]",
  standalone: true,
  imports: [RdxAccordionTriggerDirective],
  template: `<button
  rdxAccordionTrigger
  type="button"
  data-slot="accordion-trigger"
  [class]="classes()"
>
  <span class="group-hover/accordion-trigger:underline"><ng-content /></span>
  <span
    class="pointer-events-none inline-flex shrink-0 text-muted-foreground transition-transform duration-200 group-aria-expanded/accordion-trigger:rotate-180 group-aria-expanded/accordion-trigger:text-foreground motion-reduce:transition-none [&>svg]:size-5 [&>svg]:fill-current"
    data-slot="accordion-trigger-icon"
    aria-hidden="true"
    [innerHTML]="chevronIcon"
  ></span>
</button>`,
  changeDetection: ChangeDetectionStrategy.OnPush,
  hostDirectives: [RdxAccordionHeaderDirective],
  host: {
    "data-slot": "accordion-header",
    "class": "flex",
  },
})
export class AccordionTriggerComponent {
  readonly className = input<string | undefined>(undefined, { alias: "class" })

  protected readonly chevronIcon: SafeHtml =
    inject(DomSanitizer).bypassSecurityTrustHtml(CHEVRON_DOWN_SVG)

  protected readonly classes = computed(() =>
    cn("cn-accordion-trigger flex flex-1 items-center justify-between font-medium outline-none", this.className())
  )
}

@Component({
  selector: "[uiAccordionContent]",
  standalone: true,
  template: `<div class="cn-accordion-content-inner [&_a]:underline [&_a]:underline-offset-3">
  <ng-content />
</div>`,
  changeDetection: ChangeDetectionStrategy.OnPush,
  hostDirectives: [RdxAccordionPanelDirective],
  host: {
    "data-slot": "accordion-content",
    "class": "cn-accordion-content overflow-hidden",
  },
})
export class AccordionContentComponent {}
