// apps/v4/examples/aria/button-group-separator.tsx
import { Button } from "@/styles/aria-force-ui/ui/button"
import {
  ButtonGroup,
  ButtonGroupSeparator,
} from "@/styles/aria-force-ui/ui/button-group"

export default function ButtonGroupSeparatorDemo() {
  return (
    <ButtonGroup>
      <Button variant="secondary" size="sm">
        Copy
      </Button>
      <ButtonGroupSeparator />
      <Button variant="secondary" size="sm">
        Paste
      </Button>
    </ButtonGroup>
  )
}

// packages/registry-angular/examples/button-group-separator.ts
import { Button } from "@/ui/button"
import { ButtonGroup, ButtonGroupSeparator } from "@/ui/button-group"
import { Component } from "@angular/core"

@Component({
  selector: "preview-button-group-separator",
  standalone: true,
  imports: [Button, ButtonGroup, ButtonGroupSeparator],
  template: `<div uiButtonGroup>
    <button uiButton variant="secondary" size="sm">Copy</button>
    <div uiButtonGroupSeparator></div>
    <button uiButton variant="secondary" size="sm">Paste</button>
  </div>`,
})
export class ButtonGroupSeparatorDemoComponent {}

export default ButtonGroupSeparatorDemoComponent
