// apps/v4/examples/aria/input-otp-controlled.tsx
"use client"

import * as React from "react"

import {
  InputOTP,
  InputOTPGroup,
  InputOTPSlot,
} from "@/styles/aria-force-ui/ui/input-otp"

export default function InputOTPControlled() {
  const [value, setValue] = React.useState("")

  return (
    <div className="space-y-2">
      <InputOTP
        maxLength={6}
        value={value}
        onChange={(value) => setValue(value)}
      >
        <InputOTPGroup>
          <InputOTPSlot index={0} />
          <InputOTPSlot index={1} />
          <InputOTPSlot index={2} />
          <InputOTPSlot index={3} />
          <InputOTPSlot index={4} />
          <InputOTPSlot index={5} />
        </InputOTPGroup>
      </InputOTP>
      <div className="text-center text-sm">
        {value === "" ? (
          <>Enter your one-time password.</>
        ) : (
          <>You entered: {value}</>
        )}
      </div>
    </div>
  )
}

// packages/registry-angular/examples/input-otp-controlled.ts
import { InputOTP, InputOTPGroup, InputOTPSlot } from "@/ui/input-otp"
import { Component, signal } from "@angular/core"

@Component({
  selector: "preview-input-otp-controlled",
  standalone: true,
  imports: [InputOTP, InputOTPGroup, InputOTPSlot],
  template: `<div class="flex flex-col items-center gap-2">
    <div
      uiInputOtp
      aria-label="One-time password"
      [maxLength]="6"
      [(value)]="code"
    >
      <div uiInputOtpGroup>
        <div uiInputOtpSlot [index]="0"></div>
        <div uiInputOtpSlot [index]="1"></div>
        <div uiInputOtpSlot [index]="2"></div>
        <div uiInputOtpSlot [index]="3"></div>
        <div uiInputOtpSlot [index]="4"></div>
        <div uiInputOtpSlot [index]="5"></div>
      </div>
    </div>
    <p class="text-sm">
      @if (code() === "") {
        Enter your one-time password.
      } @else {
        You entered: {{ code() }}
      }
    </p>
  </div>`,
})
export class InputOtpControlledComponent {
  protected readonly code = signal("")
}

export default InputOtpControlledComponent
