// apps/v4/examples/base/input-variants.tsx
import { Input } from "@/registry/bases/base/ui/input"

export function InputVariants() {
  return (
    <div className="flex w-full flex-col gap-4">
      <Input variant="outline" placeholder="Outline" />
      <Input variant="filled" placeholder="Filled" />
      <Input variant="underline" placeholder="Underline" />
      <Input variant="ghost" placeholder="Ghost" />
    </div>
  )
}

// packages/registry-angular/examples/input-variants.ts
import { Input } from "@/ui/input"
import { Component } from "@angular/core"

@Component({
  selector: "preview-input-variants",
  standalone: true,
  imports: [Input],
  template: `<div class="flex w-full max-w-sm flex-col gap-3">
    <input uiInput variant="outline" placeholder="Outline" /><input
      uiInput
      variant="filled"
      placeholder="Filled"
    /><input uiInput variant="underline" placeholder="Underline" /><input
      uiInput
      variant="ghost"
      placeholder="Ghost"
    />
  </div>`,
})
export class InputVariantsComponent {}

export default InputVariantsComponent
