// apps/preview-angular/src/angular/badge-demo.ts
import { Badge } from "@/angular-ui/badge"
import { Component } from "@angular/core"

@Component({
  selector: "preview-badge-demo",
  standalone: true,
  imports: [Badge],
  template: ` <div class="flex flex-col items-center gap-2">
    <div class="flex w-full flex-wrap gap-2">
      <span uiBadge>Badge</span
      ><span uiBadge variant="secondary">Secondary</span>
      <span uiBadge variant="destructive">Destructive</span
      ><span uiBadge variant="outline">Outline</span>
    </div>
    <div class="flex w-full flex-wrap gap-2">
      <span uiBadge class="h-5 min-w-5 rounded-full px-1 font-mono tabular-nums"
        >8</span
      >
      <span
        uiBadge
        variant="destructive"
        class="h-5 min-w-5 rounded-full px-1 font-mono tabular-nums"
        >99</span
      >
      <span
        uiBadge
        variant="outline"
        class="h-5 min-w-5 rounded-full px-1 font-mono tabular-nums"
        >20+</span
      >
    </div>
  </div>`,
})
export class BadgeDemoComponent {}

export default BadgeDemoComponent

// apps/v4/examples/aria/badge-demo.tsx
import { Badge } from "@/styles/aria-force-ui/ui/badge"

export default function BadgeDemo() {
  return (
    <div className="flex w-full flex-wrap justify-center gap-2">
      <Badge>Badge</Badge>
      <Badge variant="secondary">Secondary</Badge>
      <Badge variant="destructive">Destructive</Badge>
      <Badge variant="outline">Outline</Badge>
    </div>
  )
}
