// apps/preview-angular/src/angular/card-demo.ts
import { Button } from "@/angular-ui/button"
import {
  Card,
  CardAction,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
} from "@/angular-ui/card"
import { Component } from "@angular/core"

@Component({
  selector: "preview-card-demo",
  standalone: true,
  imports: [
    Button,
    Card,
    CardHeader,
    CardTitle,
    CardDescription,
    CardAction,
    CardContent,
    CardFooter,
  ],
  template: ` <div uiCard class="w-full max-w-sm">
    <div uiCardHeader>
      <h3 uiCardTitle>Login to your account</h3>
      <p uiCardDescription>Enter your email below to login</p>
      <div uiCardAction><button uiButton variant="link">Sign Up</button></div>
    </div>
    <div uiCardContent>
      <div class="grid w-full items-center gap-4">
        <div class="flex flex-col space-y-1.5">
          <label class="text-sm font-medium" for="email">Email</label>
          <input
            id="email"
            type="email"
            placeholder="m@example.com"
            class="flex h-8 w-full rounded-md border border-input bg-background px-3 py-1 text-sm shadow-sm placeholder:text-muted-foreground"
          />
        </div>
      </div>
    </div>
    <div uiCardFooter class="flex-col gap-2">
      <button uiButton class="w-full">Login</button>
      <button uiButton variant="outline" class="w-full">
        Login with Google
      </button>
    </div>
  </div>`,
})
export class CardDemoComponent {}

export default CardDemoComponent

// apps/v4/examples/aria/card-demo.tsx
import { Button } from "@/registry/bases/aria/ui/button"
import {
  Card,
  CardAction,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
} from "@/registry/bases/aria/ui/card"
import { Input } from "@/registry/bases/aria/ui/input"
import { Label } from "@/registry/bases/aria/ui/label"

export default function CardDemo() {
  return (
    <Card className="w-full max-w-sm">
      <CardHeader>
        <CardTitle>Login to your account</CardTitle>
        <CardDescription>
          Enter your email below to login to your account
        </CardDescription>
        <CardAction>
          <Button variant="link">Sign Up</Button>
        </CardAction>
      </CardHeader>
      <CardContent>
        <form>
          <div className="flex flex-col gap-6">
            <div className="grid gap-2">
              <Label htmlFor="email">Email</Label>
              <Input
                id="email"
                type="email"
                placeholder="m@example.com"
                required
              />
            </div>
            <div className="grid gap-2">
              <div className="flex items-center">
                <Label htmlFor="password">Password</Label>
                <a
                  href="#"
                  className="ml-auto inline-block text-sm underline-offset-4 hover:underline"
                >
                  Forgot your password?
                </a>
              </div>
              <Input id="password" type="password" required />
            </div>
          </div>
        </form>
      </CardContent>
      <CardFooter className="flex-col gap-2">
        <Button type="submit" className="w-full">
          Login
        </Button>
        <Button variant="outline" className="w-full">
          Login with Google
        </Button>
      </CardFooter>
    </Card>
  )
}
