// apps/preview-angular/src/angular/collapsible-demo.ts
import { Button } from "@/angular-ui/button"
import {
  Collapsible,
  CollapsibleContent,
  CollapsibleTrigger,
} from "@/angular-ui/collapsible"
import { Component } from "@angular/core"

@Component({
  selector: "preview-collapsible-demo",
  standalone: true,
  imports: [Button, Collapsible, CollapsibleTrigger, CollapsibleContent],
  template: ` <div uiCollapsible class="flex w-full max-w-sm flex-col gap-2">
    <div class="flex items-center justify-between">
      <span class="text-sm font-medium"
        >&#64;shadcn starred 3 repositories</span
      >
      <button uiCollapsibleTrigger>
        <button uiButton variant="ghost" size="icon-sm" aria-label="Toggle">
          <svg
            aria-hidden="true"
            xmlns="http://www.w3.org/2000/svg"
            viewBox="0 -960 960 960"
          >
            <path d="M480-345 240-585l56-56 184 184 184-184 56 56-240 240Z" />
          </svg>
        </button>
      </button>
    </div>
    <div class="rounded-md border border-border px-4 py-3 text-sm">
      &#64;radix-ui/primitives
    </div>
    <div uiCollapsibleContent>
      <div class="flex flex-col gap-2">
        <div class="rounded-md border border-border px-4 py-3 text-sm">
          &#64;radix-ui/colors
        </div>
        <div class="rounded-md border border-border px-4 py-3 text-sm">
          &#64;stitches/react
        </div>
      </div>
    </div>
  </div>`,
})
export class CollapsibleDemoComponent {}

export default CollapsibleDemoComponent

// apps/v4/examples/aria/collapsible-demo.tsx
"use client"

import * as React from "react"
import { ChevronsUpDown } from "lucide-react"

import { Button } from "@/styles/aria-force-ui/ui/button"
import {
  Collapsible,
  CollapsibleContent,
  CollapsibleTrigger,
} from "@/styles/aria-force-ui/ui/collapsible"

export default function CollapsibleDemo() {
  const [isOpen, setIsOpen] = React.useState(false)

  return (
    <Collapsible
      isExpanded={isOpen}
      onExpandedChange={setIsOpen}
      className="flex w-[350px] flex-col gap-2"
    >
      <div className="flex items-center justify-between gap-4 px-4">
        <h4 className="text-sm font-semibold">Order #4189</h4>
        <Button slot="trigger" variant="ghost" size="icon" className="size-8">
          <ChevronsUpDown />
          <span className="sr-only">Toggle details</span>
        </Button>
      </div>
      <div className="flex items-center justify-between rounded-md border px-4 py-2 text-sm">
        <span className="text-muted-foreground">Status</span>
        <span className="font-medium">Shipped</span>
      </div>
      <CollapsibleContent>
        <div className="flex flex-col gap-2">
          <div className="rounded-md border px-4 py-2 text-sm">
            <p className="font-medium">Shipping address</p>
            <p className="text-muted-foreground">
              100 Market St, San Francisco
            </p>
          </div>
          <div className="rounded-md border px-4 py-2 text-sm">
            <p className="font-medium">Items</p>
            <p className="text-muted-foreground">2x Studio Headphones</p>
          </div>
        </div>
      </CollapsibleContent>
    </Collapsible>
  )
}
