// packages/registry-angular/examples/input-otp-demo.ts
import { InputOTP, InputOTPGroup, InputOTPSlot } from "@/ui/input-otp"
import { Component } from "@angular/core"

@Component({
  selector: "preview-input-otp-demo",
  standalone: true,
  imports: [InputOTP, InputOTPGroup, InputOTPSlot],
  template: `<div
    uiInputOtp
    aria-label="One-time password"
    [maxLength]="6"
    [value]="'123456'"
  >
    <div uiInputOtpGroup>
      <div uiInputOtpSlot [index]="0"></div>
      <div uiInputOtpSlot [index]="1"></div>
      <div uiInputOtpSlot [index]="2"></div>
      <div uiInputOtpSlot [index]="3"></div>
      <div uiInputOtpSlot [index]="4"></div>
      <div uiInputOtpSlot [index]="5"></div>
    </div>
  </div>`,
})
export class InputOtpDemoComponent {}

export default InputOtpDemoComponent

// apps/v4/examples/aria/input-otp-demo.tsx
import {
  InputOTP,
  InputOTPGroup,
  InputOTPSlot,
} from "@/styles/aria-force-ui/ui/input-otp"

export function InputOTPDemo() {
  return (
    <InputOTP maxLength={6} defaultValue="123456">
      <InputOTPGroup>
        <InputOTPSlot index={0} />
        <InputOTPSlot index={1} />
        <InputOTPSlot index={2} />
        <InputOTPSlot index={3} />
        <InputOTPSlot index={4} />
        <InputOTPSlot index={5} />
      </InputOTPGroup>
    </InputOTP>
  )
}
