// apps/preview-angular/src/angular/input-otp-alphanumeric.ts
import {
  InputOTP,
  InputOTPGroup,
  InputOTPSlot,
  REGEXP_ONLY_DIGITS_AND_CHARS,
} from "@/angular-ui/input-otp"
import { Label } from "@/angular-ui/label"
import { Component } from "@angular/core"

@Component({
  selector: "preview-input-otp-alphanumeric",
  standalone: true,
  imports: [InputOTP, InputOTPGroup, InputOTPSlot, Label],
  template: `<div class="flex flex-col gap-1.5">
    <label uiLabel for="alphanumeric">Letters and digits</label>
    <div uiInputOtp id="alphanumeric" [maxLength]="6" [pattern]="alphanumeric">
      <div uiInputOtpGroup>
        <div uiInputOtpSlot [index]="0"></div>
        <div uiInputOtpSlot [index]="1"></div>
        <div uiInputOtpSlot [index]="2"></div>
        <div uiInputOtpSlot [index]="3"></div>
        <div uiInputOtpSlot [index]="4"></div>
        <div uiInputOtpSlot [index]="5"></div>
      </div>
    </div>
  </div>`,
})
export class InputOtpAlphanumericComponent {
  protected readonly alphanumeric = REGEXP_ONLY_DIGITS_AND_CHARS
}

export default InputOtpAlphanumericComponent

// apps/v4/examples/aria/input-otp-alphanumeric.tsx
"use client"

import { REGEXP_ONLY_DIGITS_AND_CHARS } from "input-otp"

import {
  InputOTP,
  InputOTPGroup,
  InputOTPSeparator,
  InputOTPSlot,
} from "@/registry/bases/aria/ui/input-otp"

export function InputOTPAlphanumeric() {
  return (
    <InputOTP maxLength={6} pattern={REGEXP_ONLY_DIGITS_AND_CHARS}>
      <InputOTPGroup>
        <InputOTPSlot index={0} />
        <InputOTPSlot index={1} />
        <InputOTPSlot index={2} />
      </InputOTPGroup>
      <InputOTPSeparator />
      <InputOTPGroup>
        <InputOTPSlot index={3} />
        <InputOTPSlot index={4} />
        <InputOTPSlot index={5} />
      </InputOTPGroup>
    </InputOTP>
  )
}
