// apps/preview-angular/src/angular/input-otp-separator.ts
import {
  InputOTP,
  InputOTPGroup,
  InputOTPSeparator,
  InputOTPSlot,
} from "@/angular-ui/input-otp"
import { Component } from "@angular/core"

@Component({
  selector: "preview-input-otp-separator",
  standalone: true,
  imports: [InputOTP, InputOTPGroup, InputOTPSlot, InputOTPSeparator],
  template: `<div uiInputOtp aria-label="One-time password" [maxLength]="6">
    <div uiInputOtpGroup>
      <div uiInputOtpSlot [index]="0"></div>
      <div uiInputOtpSlot [index]="1"></div>
    </div>
    <div uiInputOtpSeparator></div>
    <div uiInputOtpGroup>
      <div uiInputOtpSlot [index]="2"></div>
      <div uiInputOtpSlot [index]="3"></div>
    </div>
    <div uiInputOtpSeparator></div>
    <div uiInputOtpGroup>
      <div uiInputOtpSlot [index]="4"></div>
      <div uiInputOtpSlot [index]="5"></div>
    </div>
  </div>`,
})
export class InputOtpSeparatorComponent {}

export default InputOtpSeparatorComponent

// apps/v4/examples/aria/input-otp-separator.tsx
import {
  InputOTP,
  InputOTPGroup,
  InputOTPSeparator,
  InputOTPSlot,
} from "@/registry/bases/aria/ui/input-otp"

export default function InputOTPWithSeparator() {
  return (
    <InputOTP maxLength={6}>
      <InputOTPGroup>
        <InputOTPSlot index={0} />
        <InputOTPSlot index={1} />
      </InputOTPGroup>
      <InputOTPSeparator />
      <InputOTPGroup>
        <InputOTPSlot index={2} />
        <InputOTPSlot index={3} />
      </InputOTPGroup>
      <InputOTPSeparator />
      <InputOTPGroup>
        <InputOTPSlot index={4} />
        <InputOTPSlot index={5} />
      </InputOTPGroup>
    </InputOTP>
  )
}
