// packages/registry-angular/examples/input-otp-invalid.ts
import {
  InputOTP,
  InputOTPGroup,
  InputOTPSeparator,
  InputOTPSlot,
} from "@/ui/input-otp"
import { Component } from "@angular/core"

@Component({
  selector: "preview-input-otp-invalid",
  standalone: true,
  imports: [InputOTP, InputOTPGroup, InputOTPSlot, InputOTPSeparator],
  template: `<div class="flex flex-col gap-1.5">
    <div
      uiInputOtp
      aria-label="One-time password"
      aria-invalid="true"
      aria-describedby="input-otp-invalid-error"
      [maxLength]="6"
      [value]="'000000'"
    >
      <div uiInputOtpGroup>
        <div uiInputOtpSlot [index]="0" aria-invalid="true"></div>
        <div uiInputOtpSlot [index]="1" aria-invalid="true"></div>
        <div uiInputOtpSlot [index]="2" aria-invalid="true"></div>
      </div>
      <div uiInputOtpSeparator></div>
      <div uiInputOtpGroup>
        <div uiInputOtpSlot [index]="3" aria-invalid="true"></div>
        <div uiInputOtpSlot [index]="4" aria-invalid="true"></div>
        <div uiInputOtpSlot [index]="5" aria-invalid="true"></div>
      </div>
    </div>
    <p id="input-otp-invalid-error" class="text-sm text-destructive">
      Invalid code. Try again.
    </p>
  </div>`,
})
export class InputOtpInvalidComponent {}

export default InputOtpInvalidComponent

// apps/v4/examples/aria/input-otp-invalid.tsx
"use client"

import * as React from "react"

import {
  InputOTP,
  InputOTPGroup,
  InputOTPSeparator,
  InputOTPSlot,
} from "@/registry/bases/aria/ui/input-otp"

export function InputOTPInvalid() {
  const [value, setValue] = React.useState("000000")

  return (
    <InputOTP maxLength={6} value={value} onChange={setValue}>
      <InputOTPGroup>
        <InputOTPSlot index={0} aria-invalid />
        <InputOTPSlot index={1} aria-invalid />
      </InputOTPGroup>
      <InputOTPSeparator />
      <InputOTPGroup>
        <InputOTPSlot index={2} aria-invalid />
        <InputOTPSlot index={3} aria-invalid />
      </InputOTPGroup>
      <InputOTPSeparator />
      <InputOTPGroup>
        <InputOTPSlot index={4} aria-invalid />
        <InputOTPSlot index={5} aria-invalid />
      </InputOTPGroup>
    </InputOTP>
  )
}
