// packages/registry-angular/examples/kbd-demo.ts
import { Kbd } from "@/ui/kbd"
import { Component } from "@angular/core"

@Component({
  selector: "preview-kbd-demo",
  standalone: true,
  imports: [Kbd],
  template: `<div class="flex items-center gap-2">
    <kbd uiKbd>Ctrl</kbd><kbd uiKbd>⌘K</kbd><kbd uiKbd>Ctrl + B</kbd>
  </div>`,
})
export class KbdDemoComponent {}

export default KbdDemoComponent

// apps/v4/examples/aria/kbd-demo.tsx
import { Kbd, KbdGroup } from "@/styles/aria-force-ui/ui/kbd"

export default function KbdDemo() {
  return (
    <div className="flex flex-col items-center gap-4">
      <KbdGroup>
        <Kbd>⌘</Kbd>
        <Kbd>⇧</Kbd>
        <Kbd>⌥</Kbd>
        <Kbd>⌃</Kbd>
      </KbdGroup>
      <KbdGroup>
        <Kbd>Ctrl</Kbd>
        <span>+</span>
        <Kbd>B</Kbd>
      </KbdGroup>
    </div>
  )
}
