// apps/preview-angular/src/angular/separator-vertical.ts
import { Separator } from "@/angular-ui/separator"
import { Component } from "@angular/core"

@Component({
  selector: "preview-separator-vertical",
  standalone: true,
  imports: [Separator],
  template: `<div class="flex h-5 items-center space-x-4 text-sm">
    <div>Blog</div>
    <div uiSeparator orientation="vertical"></div>
    <div>Docs</div>
    <div uiSeparator orientation="vertical"></div>
    <div>Source</div>
  </div>`,
})
export class SeparatorVerticalComponent {}

export default SeparatorVerticalComponent

// apps/v4/examples/aria/separator-vertical.tsx
import { Separator } from "@/registry/bases/aria/ui/separator"

export function SeparatorVertical() {
  return (
    <div className="flex h-5 items-center gap-4 text-sm">
      <div>Blog</div>
      <Separator orientation="vertical" />
      <div>Docs</div>
      <Separator orientation="vertical" />
      <div>Source</div>
    </div>
  )
}
