// packages/registry-angular/examples/skeleton-demo.ts
import { Skeleton } from "@/ui/skeleton"
import { Component } from "@angular/core"

@Component({
  selector: "preview-skeleton-demo",
  standalone: true,
  imports: [Skeleton],
  template: `<div class="flex items-center space-x-4">
    <div uiSkeleton class="size-12 rounded-full"></div>
    <div class="space-y-2">
      <div uiSkeleton class="h-4 w-[250px]"></div>
      <div uiSkeleton class="h-4 w-[200px]"></div>
    </div>
  </div>`,
})
export class SkeletonDemoComponent {}

export default SkeletonDemoComponent

// apps/v4/examples/aria/skeleton-demo.tsx
import { Skeleton } from "@/styles/aria-force-ui/ui/skeleton"

export function SkeletonDemo() {
  return (
    <div className="flex items-center gap-4">
      <Skeleton className="h-12 w-12 rounded-full" />
      <div className="space-y-2">
        <Skeleton className="h-4 w-[250px]" />
        <Skeleton className="h-4 w-[200px]" />
      </div>
    </div>
  )
}
