// packages/registry-angular/examples/spinner-button.ts
import { Button } from "@/ui/button"
import { Spinner } from "@/ui/spinner"
import { Component } from "@angular/core"

@Component({
  selector: "preview-spinner-button",
  standalone: true,
  imports: [Button, Spinner],
  template: `<div class="flex flex-wrap items-center gap-3">
    <button uiButton [loading]="true">Submitting…</button
    ><button uiButton variant="outline" [loading]="true">Syncing…</button
    ><button uiButton variant="ghost">
      <span uiSpinner color="inherit" data-icon="inline-start"></span>Loading
    </button>
  </div>`,
})
export class SpinnerButtonComponent {}

export default SpinnerButtonComponent

// apps/v4/examples/aria/spinner-button.tsx
import { Button } from "@/styles/aria-force-ui/ui/button"
import { Spinner } from "@/styles/aria-force-ui/ui/spinner"

export function SpinnerButton() {
  return (
    <div className="flex flex-col items-center gap-4">
      <Button isDisabled size="sm">
        <Spinner data-icon="inline-start" />
        Loading...
      </Button>
      <Button variant="outline" isDisabled size="sm">
        <Spinner data-icon="inline-start" />
        Please wait
      </Button>
      <Button variant="secondary" isDisabled size="sm">
        <Spinner data-icon="inline-start" />
        Processing
      </Button>
    </div>
  )
}
