// apps/preview-svelte/src/svelte/toggle-group-sizes.svelte
<script lang="ts">
	import * as ToggleGroup from "@/svelte-ui/toggle-group/index.js";
</script>

<div class="flex flex-col gap-4">
	<ToggleGroup.Root type="single" size="sm" value="top" variant="outline">
		<ToggleGroup.Item value="top" aria-label="Toggle top">Top</ToggleGroup.Item>
		<ToggleGroup.Item value="bottom" aria-label="Toggle bottom">Bottom</ToggleGroup.Item>
		<ToggleGroup.Item value="left" aria-label="Toggle left">Left</ToggleGroup.Item>
		<ToggleGroup.Item value="right" aria-label="Toggle right">Right</ToggleGroup.Item>
	</ToggleGroup.Root>
	<ToggleGroup.Root type="single" value="top" variant="outline">
		<ToggleGroup.Item value="top" aria-label="Toggle top">Top</ToggleGroup.Item>
		<ToggleGroup.Item value="bottom" aria-label="Toggle bottom">Bottom</ToggleGroup.Item>
		<ToggleGroup.Item value="left" aria-label="Toggle left">Left</ToggleGroup.Item>
		<ToggleGroup.Item value="right" aria-label="Toggle right">Right</ToggleGroup.Item>
	</ToggleGroup.Root>
</div>

// apps/v4/examples/aria/toggle-group-sizes.tsx
import {
  ToggleGroup,
  ToggleGroupItem,
} from "@/styles/aria-force-ui/ui/toggle-group"

export function ToggleGroupSizes() {
  return (
    <div className="flex flex-col gap-4">
      <ToggleGroup size="sm" defaultSelectedKeys={["top"]} variant="outline">
        <ToggleGroupItem id="top" aria-label="Toggle top">
          Top
        </ToggleGroupItem>
        <ToggleGroupItem id="bottom" aria-label="Toggle bottom">
          Bottom
        </ToggleGroupItem>
        <ToggleGroupItem id="left" aria-label="Toggle left">
          Left
        </ToggleGroupItem>
        <ToggleGroupItem id="right" aria-label="Toggle right">
          Right
        </ToggleGroupItem>
      </ToggleGroup>
      <ToggleGroup defaultSelectedKeys={["top"]} variant="outline">
        <ToggleGroupItem id="top" aria-label="Toggle top">
          Top
        </ToggleGroupItem>
        <ToggleGroupItem id="bottom" aria-label="Toggle bottom">
          Bottom
        </ToggleGroupItem>
        <ToggleGroupItem id="left" aria-label="Toggle left">
          Left
        </ToggleGroupItem>
        <ToggleGroupItem id="right" aria-label="Toggle right">
          Right
        </ToggleGroupItem>
      </ToggleGroup>
    </div>
  )
}
