// apps/v4/examples/base/badge-variants.tsx
import { Badge } from "@/registry/bases/base/ui/badge"

export function BadgeVariants() {
  return (
    <div className="flex flex-wrap gap-2">
      <Badge>Default</Badge>
      <Badge variant="secondary">Secondary</Badge>
      <Badge variant="destructive">Destructive</Badge>
      <Badge variant="outline">Outline</Badge>
      <Badge variant="ghost">Ghost</Badge>
    </div>
  )
}

// apps/preview-angular/src/angular/badge-variants.ts
import { Badge } from "@/angular-ui/badge"
import { Component } from "@angular/core"

@Component({
  selector: "preview-badge-variants",
  standalone: true,
  imports: [Badge],
  template: `<div class="flex flex-wrap gap-2">
    <span uiBadge>Default</span
    ><span uiBadge variant="secondary">Secondary</span
    ><span uiBadge variant="destructive">Destructive</span
    ><span uiBadge variant="outline">Outline</span
    ><span uiBadge variant="ghost">Ghost</span
    ><span uiBadge variant="link">Link</span>
  </div>`,
})
export class BadgeVariantsComponent {}

export default BadgeVariantsComponent
