// apps/v4/examples/aria/button-size.tsx
import { ArrowUpRightIcon } from "lucide-react"

import { Button } from "@/registry/bases/aria/ui/button"

export default function ButtonSize() {
  return (
    <div className="flex flex-col items-start gap-8 sm:flex-row">
      <div className="flex items-start gap-2">
        <Button size="xs" variant="outline">
          Extra Small
        </Button>
        <Button size="icon-xs" aria-label="Submit" variant="outline">
          <ArrowUpRightIcon />
        </Button>
      </div>
      <div className="flex items-start gap-2">
        <Button size="sm" variant="outline">
          Small
        </Button>
        <Button size="icon-sm" aria-label="Submit" variant="outline">
          <ArrowUpRightIcon />
        </Button>
      </div>
      <div className="flex items-start gap-2">
        <Button variant="outline">Default</Button>
        <Button size="icon" aria-label="Submit" variant="outline">
          <ArrowUpRightIcon />
        </Button>
      </div>
      <div className="flex items-start gap-2">
        <Button variant="outline" size="lg">
          Large
        </Button>
        <Button size="icon-lg" aria-label="Submit" variant="outline">
          <ArrowUpRightIcon />
        </Button>
      </div>
    </div>
  )
}

// apps/preview-angular/src/angular/button-size.ts
import { Button } from "@/angular-ui/button"
import { Component } from "@angular/core"

@Component({
  selector: "preview-button-size",
  standalone: true,
  imports: [Button],
  template: `<div class="flex flex-col items-start gap-8 sm:flex-row">
    <div class="flex items-start gap-2">
      <button uiButton size="sm" variant="outline">Small</button
      ><button uiButton size="icon-sm" variant="outline" aria-label="Submit">
        <svg
          aria-hidden="true"
          xmlns="http://www.w3.org/2000/svg"
          viewBox="0 -960 960 960"
        >
          <path
            d="M440-80v-647L256-543l-56-57 280-280 280 280-56 57-184-184v647h-80Z"
          />
        </svg>
      </button>
    </div>
    <div class="flex items-start gap-2">
      <button uiButton variant="outline">Default</button
      ><button uiButton size="icon" variant="outline" aria-label="Submit">
        <svg
          aria-hidden="true"
          xmlns="http://www.w3.org/2000/svg"
          viewBox="0 -960 960 960"
        >
          <path
            d="M440-80v-647L256-543l-56-57 280-280 280 280-56 57-184-184v647h-80Z"
          />
        </svg>
      </button>
    </div>
    <div class="flex items-start gap-2">
      <button uiButton size="lg" variant="outline">Large</button
      ><button uiButton size="icon-lg" variant="outline" aria-label="Submit">
        <svg
          aria-hidden="true"
          xmlns="http://www.w3.org/2000/svg"
          viewBox="0 -960 960 960"
        >
          <path
            d="M440-80v-647L256-543l-56-57 280-280 280 280-56 57-184-184v647h-80Z"
          />
        </svg>
      </button>
    </div>
  </div>`,
})
export class ButtonSizeComponent {}

export default ButtonSizeComponent
