// apps/v4/examples/aria/input-otp-disabled.tsx
import { Field, FieldLabel } from "@/styles/aria-force-ui/ui/field"
import {
  InputOTP,
  InputOTPGroup,
  InputOTPSeparator,
  InputOTPSlot,
} from "@/styles/aria-force-ui/ui/input-otp"

export function InputOTPDisabled() {
  return (
    <InputOTP id="disabled" maxLength={6} disabled value="123456">
      <InputOTPGroup>
        <InputOTPSlot index={0} />
        <InputOTPSlot index={1} />
        <InputOTPSlot index={2} />
      </InputOTPGroup>
      <InputOTPSeparator />
      <InputOTPGroup>
        <InputOTPSlot index={3} />
        <InputOTPSlot index={4} />
        <InputOTPSlot index={5} />
      </InputOTPGroup>
    </InputOTP>
  )
}

// apps/preview-angular/src/angular/input-otp-disabled.ts
import {
  InputOTP,
  InputOTPGroup,
  InputOTPSeparator,
  InputOTPSlot,
} from "@/angular-ui/input-otp"
import { Component } from "@angular/core"

@Component({
  selector: "preview-input-otp-disabled",
  standalone: true,
  imports: [InputOTP, InputOTPGroup, InputOTPSlot, InputOTPSeparator],
  template: `<div
    uiInputOtp
    aria-label="One-time password"
    [maxLength]="6"
    [value]="'123456'"
    [disabled]="true"
  >
    <div uiInputOtpGroup>
      <div uiInputOtpSlot [index]="0"></div>
      <div uiInputOtpSlot [index]="1"></div>
      <div uiInputOtpSlot [index]="2"></div>
    </div>
    <div uiInputOtpSeparator></div>
    <div uiInputOtpGroup>
      <div uiInputOtpSlot [index]="3"></div>
      <div uiInputOtpSlot [index]="4"></div>
      <div uiInputOtpSlot [index]="5"></div>
    </div>
  </div>`,
})
export class InputOtpDisabledComponent {}

export default InputOtpDisabledComponent
