// apps/v4/examples/aria/item-image.tsx
import Image from "next/image"

import {
  Item,
  ItemContent,
  ItemDescription,
  ItemGroup,
  ItemMedia,
  ItemTitle,
} from "@/styles/aria-force-ui/ui/item"

const music = [
  {
    title: "Midnight City Lights",
    artist: "Neon Dreams",
    album: "Electric Nights",
    duration: "3:45",
  },
  {
    title: "Coffee Shop Conversations",
    artist: "The Morning Brew",
    album: "Urban Stories",
    duration: "4:05",
  },
  {
    title: "Digital Rain",
    artist: "Cyber Symphony",
    album: "Binary Beats",
    duration: "3:30",
  },
]

export function ItemImage() {
  return (
    <div className="flex w-full max-w-md flex-col gap-6">
      <ItemGroup className="gap-4">
        {music.map((song) => (
          <Item href="#" key={song.title} variant="outline" role="listitem">
            <ItemMedia variant="image">
              <Image
                src={`https://avatar.vercel.sh/${song.title}`}
                alt={song.title}
                width={32}
                height={32}
                className="object-cover grayscale"
              />
            </ItemMedia>
            <ItemContent>
              <ItemTitle className="line-clamp-1">
                {song.title} -{" "}
                <span className="text-muted-foreground">{song.album}</span>
              </ItemTitle>
              <ItemDescription>{song.artist}</ItemDescription>
            </ItemContent>
            <ItemContent className="flex-none text-center">
              <ItemDescription>{song.duration}</ItemDescription>
            </ItemContent>
          </Item>
        ))}
      </ItemGroup>
    </div>
  )
}

// apps/preview-angular/src/angular/item-image.ts
import {
  Item,
  ItemContent,
  ItemDescription,
  ItemGroup,
  ItemMedia,
  ItemTitle,
} from "@/angular-ui/item"
import { Component } from "@angular/core"

const music = [
  {
    title: "Midnight City Lights",
    artist: "Neon Dreams",
    album: "Electric Nights",
    duration: "3:45",
  },
  {
    title: "Coffee Shop Conversations",
    artist: "The Morning Brew",
    album: "Urban Stories",
    duration: "4:05",
  },
  {
    title: "Digital Rain",
    artist: "Cyber Symphony",
    album: "Binary Beats",
    duration: "3:30",
  },
]

@Component({
  selector: "preview-item-image",
  standalone: true,
  imports: [Item, ItemGroup, ItemMedia, ItemContent, ItemTitle, ItemDescription],
  template: `<div class="flex w-full max-w-md flex-col gap-6">
    <div uiItemGroup class="gap-4">
      @for (song of music; track song.title) {
        <a uiItem variant="outline" href="#" role="listitem">
          <div uiItemMedia variant="image">
            <img
              [src]="'https://avatar.vercel.sh/' + song.title"
              [alt]="song.title"
              width="32"
              height="32"
              class="object-cover grayscale"
            />
          </div>
          <div uiItemContent>
            <div uiItemTitle class="line-clamp-1">
              {{ song.title }} -
              <span class="text-muted-foreground">{{ song.album }}</span>
            </div>
            <p uiItemDescription>{{ song.artist }}</p>
          </div>
          <div uiItemContent class="flex-none text-center">
            <p uiItemDescription>{{ song.duration }}</p>
          </div>
        </a>
      }
    </div>
  </div>`,
})
export class ItemImageComponent {
  protected readonly music = music
}

export default ItemImageComponent
