// apps/v4/examples/radix/spinner-button.tsx
import { Button } from "@/registry/bases/radix/ui/button"
import { Spinner } from "@/registry/bases/radix/ui/spinner"

export function SpinnerButton() {
  return (
    <div className="flex flex-col items-center gap-4">
      <Button disabled size="sm">
        <Spinner data-icon="inline-start" />
        Loading...
      </Button>
      <Button variant="outline" disabled size="sm">
        <Spinner data-icon="inline-start" />
        Please wait
      </Button>
      <Button variant="secondary" disabled size="sm">
        <Spinner data-icon="inline-start" />
        Processing
      </Button>
    </div>
  )
}

// apps/preview-angular/src/angular/spinner-button.ts
import { Button } from "@/angular-ui/button"
import { Spinner } from "@/angular-ui/spinner"
import { Component } from "@angular/core"

@Component({
  selector: "preview-spinner-button",
  standalone: true,
  imports: [Button, Spinner],
  template: `<div class="flex flex-wrap items-center gap-3">
    <button uiButton [loading]="true">Submitting…</button
    ><button uiButton variant="outline" [loading]="true">Syncing…</button
    ><button uiButton variant="ghost">
      <span uiSpinner color="inherit" data-icon="inline-start"></span>Loading
    </button>
  </div>`,
})
export class SpinnerButtonComponent {}

export default SpinnerButtonComponent
