// apps/v4/examples/radix/spinner-colors.tsx
import { Spinner } from "@/registry/bases/radix/ui/spinner"

export function SpinnerColors() {
  return (
    <div className="flex items-center gap-6">
      <Spinner color="default" />
      <Spinner color="primary" />
      <Spinner color="inherit" />
      <div className="rounded-md bg-primary p-2">
        <Spinner color="onPrimary" />
      </div>
    </div>
  )
}

// apps/preview-angular/src/angular/spinner-colors.ts
import { Spinner } from "@/angular-ui/spinner"
import { Component } from "@angular/core"

@Component({
  selector: "preview-spinner-colors",
  standalone: true,
  imports: [Spinner],
  template: `<div class="flex items-center gap-4">
    <span uiSpinner color="default" size="md"></span
    ><span uiSpinner color="primary" size="md"></span>
    <div class="rounded-lg bg-primary p-2">
      <span uiSpinner color="onPrimary" size="md"></span>
    </div>
  </div>`,
})
export class SpinnerColorsComponent {}

export default SpinnerColorsComponent
