// apps/v4/examples/aria/table-rtl.tsx
"use client"

import * as React from "react"

import {
  useTranslation,
  type Translations,
} from "@/components/language-selector"
import {
  Table,
  TableBody,
  TableCaption,
  TableCell,
  TableFooter,
  TableHead,
  TableHeader,
  TableRow,
} from "@/styles/aria-force-ui/ui-rtl/table"

const translations: Translations = {
  en: {
    dir: "ltr",
    values: {
      caption: "A list of your recent invoices.",
      invoice: "Invoice",
      status: "Status",
      method: "Method",
      amount: "Amount",
      paid: "Paid",
      pending: "Pending",
      unpaid: "Unpaid",
      creditCard: "Credit Card",
      paypal: "PayPal",
      bankTransfer: "Bank Transfer",
      total: "Total",
    },
  },
  ar: {
    dir: "rtl",
    values: {
      caption: "قائمة بفواتيرك الأخيرة.",
      invoice: "الفاتورة",
      status: "الحالة",
      method: "الطريقة",
      amount: "المبلغ",
      paid: "مدفوع",
      pending: "قيد الانتظار",
      unpaid: "غير مدفوع",
      creditCard: "بطاقة ائتمانية",
      paypal: "PayPal",
      bankTransfer: "تحويل بنكي",
      total: "المجموع",
    },
  },
  he: {
    dir: "rtl",
    values: {
      caption: "רשימת החשבוניות האחרונות שלך.",
      invoice: "חשבונית",
      status: "סטטוס",
      method: "שיטה",
      amount: "סכום",
      paid: "שולם",
      pending: "ממתין",
      unpaid: "לא שולם",
      creditCard: "כרטיס אשראי",
      paypal: "PayPal",
      bankTransfer: "העברה בנקאית",
      total: 'סה"כ',
    },
  },
}

const invoices = [
  {
    invoice: "INV001",
    paymentStatus: "paid" as const,
    totalAmount: "$250.00",
    paymentMethod: "creditCard" as const,
  },
  {
    invoice: "INV002",
    paymentStatus: "pending" as const,
    totalAmount: "$150.00",
    paymentMethod: "paypal" as const,
  },
  {
    invoice: "INV003",
    paymentStatus: "unpaid" as const,
    totalAmount: "$350.00",
    paymentMethod: "bankTransfer" as const,
  },
  {
    invoice: "INV004",
    paymentStatus: "paid" as const,
    totalAmount: "$450.00",
    paymentMethod: "creditCard" as const,
  },
  {
    invoice: "INV005",
    paymentStatus: "paid" as const,
    totalAmount: "$550.00",
    paymentMethod: "paypal" as const,
  },
  {
    invoice: "INV006",
    paymentStatus: "pending" as const,
    totalAmount: "$200.00",
    paymentMethod: "bankTransfer" as const,
  },
  {
    invoice: "INV007",
    paymentStatus: "unpaid" as const,
    totalAmount: "$300.00",
    paymentMethod: "creditCard" as const,
  },
]

export function TableRtl() {
  const { dir, t } = useTranslation(translations, "ar")

  return (
    <figure className="w-full">
      <Table dir={dir} aria-label={t.caption}>
        <TableHeader>
          <TableHead isRowHeader className="w-[100px]">
            {t.invoice}
          </TableHead>
          <TableHead>{t.status}</TableHead>
          <TableHead>{t.method}</TableHead>
          <TableHead className="text-right">{t.amount}</TableHead>
        </TableHeader>
        <TableBody>
          {invoices.map((invoice) => (
            <TableRow key={invoice.invoice}>
              <TableCell className="font-medium">{invoice.invoice}</TableCell>
              <TableCell>{t[invoice.paymentStatus]}</TableCell>
              <TableCell>{t[invoice.paymentMethod]}</TableCell>
              <TableCell className="text-right">
                {invoice.totalAmount}
              </TableCell>
            </TableRow>
          ))}
        </TableBody>
        <TableFooter>
          <TableRow>
            <TableCell colSpan={3}>{t.total}</TableCell>
            <TableCell className="text-right">$2,500.00</TableCell>
          </TableRow>
        </TableFooter>
      </Table>
      <TableCaption>{t.caption}</TableCaption>
    </figure>
  )
}

// apps/preview-angular/src/angular/table-rtl.ts
import {
  Table,
  TableBody,
  TableCaption,
  TableCell,
  TableContainer,
  TableFooter,
  TableHead,
  TableHeader,
  TableRow,
} from "@/angular-ui/table"
import { Component } from "@angular/core"

const invoices = [
  {
    invoice: "INV001",
    paymentStatus: "مدفوع",
    totalAmount: "$250.00",
    paymentMethod: "بطاقة ائتمانية",
  },
  {
    invoice: "INV002",
    paymentStatus: "قيد الانتظار",
    totalAmount: "$150.00",
    paymentMethod: "PayPal",
  },
  {
    invoice: "INV003",
    paymentStatus: "غير مدفوع",
    totalAmount: "$350.00",
    paymentMethod: "تحويل بنكي",
  },
  {
    invoice: "INV004",
    paymentStatus: "مدفوع",
    totalAmount: "$450.00",
    paymentMethod: "بطاقة ائتمانية",
  },
  {
    invoice: "INV005",
    paymentStatus: "مدفوع",
    totalAmount: "$550.00",
    paymentMethod: "PayPal",
  },
  {
    invoice: "INV006",
    paymentStatus: "قيد الانتظار",
    totalAmount: "$200.00",
    paymentMethod: "تحويل بنكي",
  },
  {
    invoice: "INV007",
    paymentStatus: "غير مدفوع",
    totalAmount: "$300.00",
    paymentMethod: "بطاقة ائتمانية",
  },
]

@Component({
  selector: "preview-table-rtl",
  standalone: true,
  imports: [
    TableContainer,
    Table,
    TableCaption,
    TableHeader,
    TableBody,
    TableFooter,
    TableRow,
    TableHead,
    TableCell,
  ],
  template: ` <div uiTableContainer>
    <table uiTable dir="rtl">
      <caption uiTableCaption>
        قائمة بفواتيرك الأخيرة.
      </caption>
      <thead uiTableHeader>
        <tr uiTableRow>
          <th uiTableHead class="w-[100px]">الفاتورة</th>
          <th uiTableHead>الحالة</th>
          <th uiTableHead>الطريقة</th>
          <th uiTableHead class="text-right">المبلغ</th>
        </tr>
      </thead>
      <tbody uiTableBody>
        @for (invoice of invoices; track invoice.invoice) {
          <tr uiTableRow>
            <td uiTableCell class="font-medium">{{ invoice.invoice }}</td>
            <td uiTableCell>{{ invoice.paymentStatus }}</td>
            <td uiTableCell>{{ invoice.paymentMethod }}</td>
            <td uiTableCell class="text-right">{{ invoice.totalAmount }}</td>
          </tr>
        }
      </tbody>
      <tfoot uiTableFooter>
        <tr uiTableRow>
          <td uiTableCell colspan="3">المجموع</td>
          <td uiTableCell class="text-right">$2,500.00</td>
        </tr>
      </tfoot>
    </table>
  </div>`,
})
export class TableRtlComponent {
  protected readonly invoices = invoices
}

export default TableRtlComponent
