// packages/registry-angular/examples/badge-solid.ts
import { Badge } from "@/ui/badge"
import { Component } from "@angular/core"

@Component({
  selector: "preview-badge-solid",
  standalone: true,
  imports: [Badge],
  template: `<div class="flex flex-wrap gap-2">
    <span uiBadge variant="success-solid">Deployed</span
    ><span uiBadge variant="warning-solid">Expiring</span
    ><span uiBadge variant="info-solid">Beta</span
    ><span uiBadge variant="error-solid">Failed</span>
  </div>`,
})
export class BadgeSolidComponent {}

export default BadgeSolidComponent

// apps/v4/examples/base/badge-solid.tsx
import { Badge } from "@/registry/bases/base/ui/badge"

export function BadgeSolid() {
  return (
    <div className="flex flex-wrap gap-2">
      <Badge variant="success-solid">Success</Badge>
      <Badge variant="warning-solid">Warning</Badge>
      <Badge variant="info-solid">Info</Badge>
      <Badge variant="error-solid">Error</Badge>
    </div>
  )
}
