// apps/preview-angular/src/angular/pagination-simple.ts
import {
  Pagination,
  PaginationContent,
  PaginationItem,
  PaginationLink,
} from "@/angular-ui/pagination"
import { Component } from "@angular/core"

@Component({
  selector: "preview-pagination-simple",
  standalone: true,
  imports: [Pagination, PaginationContent, PaginationItem, PaginationLink],
  template: `<nav uiPagination>
    <ul uiPaginationContent>
      <li uiPaginationItem><a uiPaginationLink href="#">1</a></li>
      <li uiPaginationItem>
        <a uiPaginationLink href="#" isActive>2</a>
      </li>
      <li uiPaginationItem><a uiPaginationLink href="#">3</a></li>
      <li uiPaginationItem><a uiPaginationLink href="#">4</a></li>
      <li uiPaginationItem><a uiPaginationLink href="#">5</a></li>
    </ul>
  </nav>`,
})
export class PaginationSimpleComponent {}

export default PaginationSimpleComponent

// apps/v4/examples/base/pagination-simple.tsx
import {
  Pagination,
  PaginationContent,
  PaginationItem,
  PaginationLink,
} from "@/registry/bases/base/ui/pagination"

export function PaginationSimple() {
  return (
    <Pagination>
      <PaginationContent>
        <PaginationItem>
          <PaginationLink href="#">1</PaginationLink>
        </PaginationItem>
        <PaginationItem>
          <PaginationLink href="#" isActive>
            2
          </PaginationLink>
        </PaginationItem>
        <PaginationItem>
          <PaginationLink href="#">3</PaginationLink>
        </PaginationItem>
        <PaginationItem>
          <PaginationLink href="#">4</PaginationLink>
        </PaginationItem>
        <PaginationItem>
          <PaginationLink href="#">5</PaginationLink>
        </PaginationItem>
      </PaginationContent>
    </Pagination>
  )
}
