// templates/designer-template/src/components/ui/radio-group.tsx
import { Radio as RadioPrimitive } from "@base-ui/react/radio"
import { RadioGroup as RadioGroupPrimitive } from "@base-ui/react/radio-group"

import { cn } from "@/lib/utils"

function RadioGroup({ className, ...props }: RadioGroupPrimitive.Props) {
  return (
    <RadioGroupPrimitive
      data-slot="radio-group"
      className={cn("grid w-full gap-2", className)}
      {...props}
    />
  )
}

function RadioGroupItem({ className, ...props }: RadioPrimitive.Root.Props) {
  return (
    <RadioPrimitive.Root
      data-slot="radio-group-item"
      className={cn(
        "group/radio-group-item peer relative flex aspect-square size-4 shrink-0 rounded-full border border-input bg-background transition-colors outline-none after:absolute after:-inset-x-3 after:-inset-y-2 focus-visible:border-ring focus-visible:ring-3 focus-visible:ring-ring/50 enabled:cursor-pointer disabled:cursor-not-allowed disabled:opacity-50 aria-invalid:border-destructive aria-invalid:ring-3 aria-invalid:ring-destructive/20 aria-invalid:aria-checked:border-primary motion-reduce:transition-none dark:bg-input/30 dark:aria-invalid:ring-destructive/40 data-checked:border-primary data-checked:bg-primary data-checked:text-primary-foreground dark:data-checked:bg-primary",
        className
      )}
      {...props}
    >
      <RadioPrimitive.Indicator
        data-slot="radio-group-indicator"
        className="flex size-4 items-center justify-center"
      >
        <span className="absolute top-1/2 left-1/2 size-2 -translate-x-1/2 -translate-y-1/2 rounded-full bg-primary-foreground" />
      </RadioPrimitive.Indicator>
    </RadioPrimitive.Root>
  )
}

export { RadioGroup, RadioGroupItem }

// packages/registry-angular/ui/radio-group/radio-group.component.ts
import { ChangeDetectionStrategy, Component, computed, input } from "@angular/core"
import { RdxRadioGroupDirective, RdxRadioIndicatorDirective, RdxRadioItemDirective } from "@radix-ng/primitives/radio"

import { cn } from "@/lib/utils"

/**
 * Angular port of @force-ui/radio-group (radix-force-ui style).
 *
 * Usage:
 *   <div uiRadioGroup [(value)]="selected">
 *     <button uiRadioGroupItem value="option-1"></button>
 *     <label>Option 1</label>
 *   </div>
 */
@Component({
  selector: "[uiRadioGroup]",
  standalone: true,
  template: "<ng-content />",
  changeDetection: ChangeDetectionStrategy.OnPush,
  hostDirectives: [
    {
      directive: RdxRadioGroupDirective,
      inputs: ["value", "defaultValue", "disabled", "required", "orientation"],
      outputs: ["valueChange", "onValueChange"],
    },
  ],
  host: {
    "data-slot": "radio-group",
    "[class]": "classes()",
  },
})
export class RadioGroupComponent {
  readonly className = input<string | undefined>(undefined, { alias: "class" })
  protected readonly classes = computed(() => cn("cn-radio-group grid w-full", this.className()))
}

@Component({
  selector: "button[uiRadioGroupItem]",
  standalone: true,
  imports: [RdxRadioIndicatorDirective],
  templateUrl: "./radio-group-item.component.html",
  changeDetection: ChangeDetectionStrategy.OnPush,
  hostDirectives: [
    {
      directive: RdxRadioItemDirective,
      inputs: ["value", "id", "required", "disabled"],
    },
  ],
  host: {
    "data-slot": "radio-group-item",
    "[class]": "classes()",
  },
})
export class RadioGroupItemComponent {
  readonly className = input<string | undefined>(undefined, { alias: "class" })
  protected readonly classes = computed(() =>
    cn(
      "cn-radio-group-item peer relative flex aspect-square shrink-0 cursor-pointer rounded-full border transition-colors motion-reduce:transition-none outline-none focus-visible:ring-3 aria-invalid:ring-3 disabled:cursor-not-allowed disabled:opacity-50",
      this.className()
    )
  )
}
