// templates/designer-template/src/components/ui/checkbox.tsx
"use client"

import { Checkbox as CheckboxPrimitive } from "@base-ui/react/checkbox"

import { cn } from "@/lib/utils"
import { MinusIcon, CheckIcon } from "@/lib/material-symbols"

function Checkbox({
  className,
  indeterminate,
  ...props
}: CheckboxPrimitive.Root.Props) {
  return (
    <CheckboxPrimitive.Root
      data-slot="checkbox"
      indeterminate={indeterminate}
      className={cn(
        "peer relative flex size-4 shrink-0 items-center justify-center rounded-[4px] border border-input bg-background transition-colors outline-none group-has-disabled/field:opacity-50 after:absolute after:-inset-x-3 after:-inset-y-2 focus-visible:border-ring focus-visible:ring-3 focus-visible:ring-ring/50 disabled:cursor-not-allowed disabled:opacity-50 aria-invalid:border-destructive aria-invalid:ring-3 aria-invalid:ring-destructive/20 aria-invalid:aria-checked:border-primary data-[state=indeterminate]:border-primary data-[state=indeterminate]:bg-primary data-[state=indeterminate]:text-primary-foreground enabled:data-[state=indeterminate]:hover:bg-primary-hover enabled:data-[state=unchecked]:hover:bg-primary-subtle motion-reduce:transition-none dark:bg-input/30 dark:aria-invalid:border-destructive/50 dark:aria-invalid:ring-destructive/40 dark:data-[state=indeterminate]:bg-primary data-checked:border-primary data-checked:bg-primary data-checked:text-primary-foreground enabled:data-checked:hover:bg-primary-hover dark:data-checked:bg-primary",
        className
      )}
      {...props}
    >
      <CheckboxPrimitive.Indicator
        data-slot="checkbox-indicator"
        className="grid place-content-center text-current transition-none [&>svg]:size-3.5"
      >
        {indeterminate ? (
          // [FORCE-UI] dash glyph for the indeterminate state, distinct from checked
          <MinusIcon materialSymbols="remove" />
        ) : (
          <CheckIcon materialSymbols="check" />
        )}
      </CheckboxPrimitive.Indicator>
    </CheckboxPrimitive.Root>
  )
}

export { Checkbox }

// packages/registry-angular/ui/checkbox/checkbox.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  inject,
} from "@angular/core"
import { DomSanitizer, type SafeHtml } from "@angular/platform-browser"
import {
  injectCheckboxRootContext,
  RdxCheckboxButtonDirective,
  RdxCheckboxIndicatorDirective,
  RdxCheckboxRootDirective,
} from "@radix-ng/primitives/checkbox"

import { cn } from "@/lib/utils"

// Inline Material Symbols Rounded SVGs
const CHECK_SVG = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 -960 960 960"><path d="M382-240 154-468l57-57 171 171 367-367 57 57-424 424Z"/></svg>`
const INDETERMINATE_SVG = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 -960 960 960"><path d="M200-440v-80h560v80H200Z"/></svg>`

/**
 * Angular port of @force-ui/checkbox (radix-force-ui style).
 *
 * Attribute selector on a native <button> — usage:
 *   <button uiCheckbox [(checked)]="checked"></button>
 *   <button uiCheckbox [checked]="'indeterminate'"></button>
 *
 * The checked state, keyboard interaction, and ARIA are handled by
 * RdxCheckboxRootDirective. Pair with a <label> for accessible naming.
 */
@Component({
  selector: "button[uiCheckbox]",
  standalone: true,
  imports: [RdxCheckboxIndicatorDirective],
  templateUrl: "./checkbox.component.html",
  changeDetection: ChangeDetectionStrategy.OnPush,
  hostDirectives: [
    {
      directive: RdxCheckboxRootDirective,
      inputs: ["checked", "value", "disabled", "required", "name"],
      outputs: ["checkedChange", "onCheckedChange"],
    },
    RdxCheckboxButtonDirective,
  ],
  host: {
    "data-slot": "checkbox",
    "[class]": "classes()",
  },
})
export class CheckboxComponent {
  private readonly ctx = injectCheckboxRootContext()
  private readonly sanitizer = inject(DomSanitizer)

  protected readonly indicatorIcon = computed<SafeHtml>(() => {
    const state = this.ctx.state()
    const svg = state === "indeterminate" ? INDETERMINATE_SVG : CHECK_SVG
    return this.sanitizer.bypassSecurityTrustHtml(svg)
  })

  protected readonly classes = computed(() =>
    cn(
      "cn-checkbox peer relative flex shrink-0 cursor-pointer items-center justify-center rounded-[4px] border transition-colors motion-reduce:transition-none outline-none focus-visible:ring-3 aria-invalid:ring-3 disabled:cursor-not-allowed disabled:opacity-50",
    )
  )
}

<span
  rdxCheckboxIndicator
  data-slot="checkbox-indicator"
  class="cn-checkbox-indicator grid place-content-center text-current transition-none [&>svg]:fill-current"
  aria-hidden="true"
  [innerHTML]="indicatorIcon()"
></span>
