// apps/preview-angular/src/angular/aspect-ratio-demo.ts
import { AspectRatio } from "@/angular-ui/aspect-ratio"
import { Component } from "@angular/core"

@Component({
  selector: "preview-aspect-ratio-demo",
  standalone: true,
  imports: [AspectRatio],
  template: `<div
    uiAspectRatio
    [ratio]="16 / 9"
    class="w-full max-w-sm overflow-hidden rounded-lg bg-muted"
  >
    <img
      src="https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800"
      alt="Mountain"
      class="size-full object-cover"
    />
  </div>`,
})
export class AspectRatioDemoComponent {}

export default AspectRatioDemoComponent

// apps/v4/examples/radix/aspect-ratio-demo.tsx
import Image from "next/image"

import { AspectRatio } from "@/registry/bases/radix/ui/aspect-ratio"

export default function AspectRatioDemo() {
  return (
    <div className="w-full max-w-sm">
      <AspectRatio ratio={16 / 9} className="rounded-lg bg-muted">
        <Image
          src="https://avatar.vercel.sh/shadcn1"
          alt="Photo"
          fill
          className="w-full rounded-lg object-cover grayscale dark:brightness-20"
        />
      </AspectRatio>
    </div>
  )
}
