// apps/preview-angular/src/angular/radio-group-demo.ts
import { Label } from "@/angular-ui/label"
import { RadioGroup, RadioGroupItem } from "@/angular-ui/radio-group"
import { Component } from "@angular/core"

@Component({
  selector: "preview-radio-group-demo",
  standalone: true,
  imports: [RadioGroup, RadioGroupItem, Label],
  template: ` <div uiRadioGroup defaultValue="option-1" class="gap-3">
    <div class="flex items-center gap-2">
      <button uiRadioGroupItem id="r1" value="option-1"></button>
      <label uiLabel for="r1">Default</label>
    </div>
    <div class="flex items-center gap-2">
      <button uiRadioGroupItem id="r2" value="option-2"></button>
      <label uiLabel for="r2">Comfortable</label>
    </div>
    <div class="flex items-center gap-2">
      <button uiRadioGroupItem id="r3" value="option-3"></button>
      <label uiLabel for="r3">Compact</label>
    </div>
  </div>`,
})
export class RadioGroupDemoComponent {}

export default RadioGroupDemoComponent

// apps/v4/examples/radix/radio-group-demo.tsx
import { Label } from "@/registry/bases/radix/ui/label"
import {
  RadioGroup,
  RadioGroupItem,
} from "@/registry/bases/radix/ui/radio-group"

export function RadioGroupDemo() {
  return (
    <RadioGroup defaultValue="comfortable" className="w-fit">
      <div className="flex items-center gap-3">
        <RadioGroupItem value="default" id="r1" />
        <Label htmlFor="r1">Default</Label>
      </div>
      <div className="flex items-center gap-3">
        <RadioGroupItem value="comfortable" id="r2" />
        <Label htmlFor="r2">Comfortable</Label>
      </div>
      <div className="flex items-center gap-3">
        <RadioGroupItem value="compact" id="r3" />
        <Label htmlFor="r3">Compact</Label>
      </div>
    </RadioGroup>
  )
}
